version: "3.9"
services:
  dev:
    build: .
    env_file: .env
    volumes:
      - .:/src/project
      - /var/sinz-shared:/data
    entrypoint: /bin/bash -c "sleep infinity"
    container_name: suhas_dev_2_gpu0
